package com.tauk.datarule.util;

import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;

public class RuleUtil_Max_Min_Null {

	/**************** 获取sgrdb pms库连接 ***********************/
	public static Connection getConnect() {
		Connection con = null;
		
		 InputStream inputStream = JDBCHelper.class.getClassLoader().getResourceAsStream("jdbc-pms.properties");
         Properties properties = new Properties();
         try {
			properties.load(inputStream);
		} catch (IOException e1) {
			e1.printStackTrace();
		}
         
		String Url = properties.getProperty("url");
		String name = properties.getProperty("username");
		String psd = properties.getProperty("password");
		String jdbcName = properties.getProperty("driverClassName");
		try {
			Class.forName(jdbcName);
			con = DriverManager.getConnection(Url, name, psd);
		} catch (Exception e) {
			e.printStackTrace();
		}
		return con;
	}

	/**************** 获取参数核查库连接 ***********************/
	public static Connection getConnect2() {
		Connection con = null;
		 InputStream inputStream = JDBCHelper.class.getClassLoader().getResourceAsStream("jdbc.properties");
         Properties properties = new Properties();
         try {
			properties.load(inputStream);
		} catch (IOException e1) {
			e1.printStackTrace();
		}
         
		String Url = properties.getProperty("url");
		String name = properties.getProperty("username");
		String psd = properties.getProperty("password");
		String jdbcName = properties.getProperty("driverClassName");
		try {
			Class.forName(jdbcName);
			con = DriverManager.getConnection(Url, name, psd);
		} catch (Exception e) {
			e.printStackTrace();
		}
		return con;
	}

	/**********
	 * 清空表t_rule_datastatistic
	 * 
	 * @throws SQLException
	 **********/
	public static void cleanTable_datastatistic() {
		String sql = "truncate table t_rule_datastatistics";
		Connection con = getConnect2();
		PreparedStatement pst = null;
		try {
			pst = con.prepareStatement(sql);
			pst.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		} finally {
			try {
				con.close();
				pst.close();
			} catch (SQLException e) {
				e.printStackTrace();
			}
		}
	}

	/******
	 * 将ResultSetMetaData获取的列名封装到list中
	 * 
	 * @throws SQLException
	 ******/
	public static List<String> queryName2List(ResultSetMetaData data) throws SQLException {
		List<String> list = new ArrayList<String>();
		try {
			int count = data.getColumnCount();
			for (int i = 1; i <= count; i++) {
				list.add(data.getColumnName(i));
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		return list;
	}

	/****************
	 * 添加数据
	 * 
	 * @throws SQLException
	 ***********************/
	public static void insertStatisticsData(int ruleid, String statisticstype, String statisticsvalue,
			String groupcolumn) {
		String sql = "insert into t_rule_datastatistics (ruleid,statisticstype,statisticsvalue,groupcolumn) values(?,?,?,?)";
		Connection con = getConnect2();
		PreparedStatement pst = null;
		try {
			pst = con.prepareStatement(sql);
			pst.setInt(1, ruleid);
			pst.setString(2, statisticstype);
			pst.setString(3, statisticsvalue);
			pst.setString(4, groupcolumn);
			pst.executeUpdate();
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			try {
				con.close();
				pst.close();
			} catch (SQLException e) {
				e.printStackTrace();
			}
		}

	}

	/********* 获取ruleid与columnname的对应关系 *********/
	public static Map<String, Integer> queryRuleData(String name) {
		String sql = "select ruleid,columnname,columntype from t_rule_data where columntype like '%NUMBER%' and tname=?";
		Map<String, Integer> map = null;
		PreparedStatement rule_data = null;
		Connection con = null;
		try {
			con = getConnect2();
			rule_data = con.prepareStatement(sql);
			rule_data.setString(1, name);
			ResultSet rs = rule_data.executeQuery();
			map = new HashMap<String, Integer>();
			while (rs.next()) {
				map.put(rs.getString(2), rs.getInt(1));
			}
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			try {
				con.close();
				rule_data.close();
			} catch (SQLException e) {
				e.printStackTrace();
			}

		}

		return map;
	}

	/*************
	 * 转换和清洗数据
	 * 
	 * @throws SQLException
	 ****************/
	public static void cleanData(ResultSet query, Map<String, Integer> map, List<String> list) throws SQLException {
		/******** 定义数据变量 ********/
		Integer ruleID = null;
		String statisticstype = null;
		String statisticsvalue = null;
		String groupcolumn = null;
		/********** 根据列名分类数据 ***************/
		while (query.next()) {
			for (String key : map.keySet()) {
				for (int j = 0; j < list.size(); j++) {
					// 是否在map中，即所查的表列字段是否在总表中。
					boolean IsExit = list.get(j).contains(key);
					if (IsExit) {
						/***** 列名中包含MAX字段 ****/
						if (list.get(j).toUpperCase().contains("_MAX")) {
							statisticstype = "max";
							/***** 列名中包含MIN字段 ****/
						} else if (list.get(j).toUpperCase().contains("_MIN")) {
							statisticstype = "min";
							/***** 列名中包含null_num字段 ****/
						} else if (list.get(j).contains("_null_num")) {
							statisticstype = "null_num";
						}
						statisticsvalue = query.getString(list.get(j));
						String sccj = query.getString(1);
						String xh = query.getString(3);
						// 非空才入库
						if (statisticsvalue != null && !statisticsvalue.equals("") && sccj != null & xh != null) {
							ruleID = map.get(key);
							groupcolumn = "sccj=" + sccj + "," + "xh=" + xh;
							insertStatisticsData(ruleID, statisticstype, statisticsvalue, groupcolumn);
						}
					}

				}
			}
		}
	}

	/*************** 封装sql语句和查询名称 **************/
	public static void cleanAndTranslateData(String sql, String name) {
		List<String> rowList_tou = null;
		Connection con = null;
		PreparedStatement sql_data = null;
		try {
			con = getConnect();
			sql_data = con.prepareStatement(sql);
			ResultSet executeQuery = sql_data.executeQuery();
			executeQuery.last();
			int row = executeQuery.getRow();
			executeQuery.first();
			if (row < 1) {
				return;
			}
			ResultSetMetaData data = executeQuery.getMetaData();
			rowList_tou = queryName2List(data);
			Map<String, Integer> map = queryRuleData(name);
			cleanData(executeQuery, map, rowList_tou);
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			try {
				con.close();
				sql_data.close();
			} catch (SQLException e) {
				e.printStackTrace();
			}
		}
	}

	public static void main(String[] args) {
		// 建立sql语句和查询名称的映射
		System.out.println("running");
		Map<String, String> sqlNameMap = new HashMap<String, String>();
		String sql_sb_zbyq = "SELECT t.SCCJ AS 'sccj', t1.SCCJMC AS 'sccjmc', t.XH AS 'xh', MAX(t.EDPL) AS 'EDPL_MAX' , MIN(t.EDPL) AS 'EDPL_MIN', SUM(CASE  WHEN t.EDPL IS NULL THEN 1 ELSE 0 END) AS 'EDPL_null_num' , MAX(t.ZLQRL) AS 'ZLQRL_MAX', MIN(t.ZLQRL) AS 'ZLQRL_MIN' , SUM(CASE  WHEN t.ZLQRL IS NULL THEN 1 ELSE 0 END) AS 'ZLQRL_null_num', MAX(t.EDDLZY) AS 'EDDLZY_MAX' , MIN(t.EDDLZY) AS 'EDDLZY_MIN', SUM(CASE  WHEN t.EDDLZY IS NULL THEN 1 ELSE 0 END) AS 'EDDLZY_null_num' , MAX(t.FZSHGYDY) AS 'FZSHGYDY_MAX', MIN(t.FZSHGYDY) AS 'FZSHGYDY_MIN' , SUM(CASE  WHEN t.FZSHGYDY IS NULL THEN 1 ELSE 0 END) AS 'FZSHGYDY_null_num', MAX(t.FZSHZYDY) AS 'FZSHZYDY_MAX' , MIN(t.FZSHZYDY) AS 'FZSHZYDY_MIN', SUM(CASE  WHEN t.FZSHZYDY IS NULL THEN 1 ELSE 0 END) AS 'FZSHZYDY_null_num' , MAX(t.DLZKGYDY) AS 'DLZKGYDY_MAX', MIN(t.DLZKGYDY) AS 'DLZKGYDY_MIN' , SUM(CASE  WHEN t.DLZKGYDY IS NULL THEN 1 ELSE 0 END) AS 'DLZKGYDY_null_num', MAX(t.KZDL) AS 'KZDL_MAX' , MIN(t.KZDL) AS 'KZDL_MIN', SUM(CASE  WHEN t.KZDL IS NULL THEN 1 ELSE 0 END) AS 'KZDL_null_num' , MAX(t.FZSHMZ) AS 'FZSHMZ_MAX', MIN(t.FZSHMZ) AS 'FZSHMZ_MIN' , SUM(CASE  WHEN t.FZSHMZ IS NULL THEN 1 ELSE 0 END) AS 'FZSHMZ_null_num', MAX(t.SF6QTBJYL) AS 'SF6QTBJYL_MAX' , MIN(t.SF6QTBJYL) AS 'SF6QTBJYL_MIN', SUM(CASE  WHEN t.SF6QTBJYL IS NULL THEN 1 ELSE 0 END) AS 'SF6QTBJYL_null_num' , MAX(t.YSZ) AS 'YSZ_MAX', MIN(t.YSZ) AS 'YSZ_MIN' , SUM(CASE  WHEN t.YSZ IS NULL THEN 1 ELSE 0 END) AS 'YSZ_null_num', MAX(t.YZRL) AS 'YZRL_MAX' , MIN(t.YZRL) AS 'YZRL_MIN', SUM(CASE  WHEN t.YZRL IS NULL THEN 1 ELSE 0 END) AS 'YZRL_null_num' , MAX(t.SF6QTZL) AS 'SF6QTZL_MAX', MIN(t.SF6QTZL) AS 'SF6QTZL_MIN' , SUM(CASE  WHEN t.SF6QTZL IS NULL THEN 1 ELSE 0 END) AS 'SF6QTZL_null_num', MAX(t.SF6QZDLC) AS 'SF6QZDLC_MAX' , MIN(t.SF6QZDLC) AS 'SF6QZDLC_MIN', SUM(CASE  WHEN t.SF6QZDLC IS NULL THEN 1 ELSE 0 END) AS 'SF6QZDLC_null_num' , MAX(t.SF6QZBT) AS 'SF6QZBT_MAX', MIN(t.SF6QZBT) AS 'SF6QZBT_MIN' , SUM(CASE  WHEN t.SF6QZBT IS NULL THEN 1 ELSE 0 END) AS 'SF6QZBT_null_num', MAX(t.SF6QZYZKG) AS 'SF6QZYZKG_MAX' , MIN(t.SF6QZYZKG) AS 'SF6QZYZKG_MIN', SUM(CASE  WHEN t.SF6QZYZKG IS NULL THEN 1 ELSE 0 END) AS 'SF6QZYZKG_null_num' , MAX(t.EDDL) AS 'EDDL_MAX', MIN(t.EDDL) AS 'EDDL_MIN' , SUM(CASE  WHEN t.EDDL IS NULL THEN 1 ELSE 0 END) AS 'EDDL_null_num', MAX(t.EDRL) AS 'EDRL_MAX' , MIN(t.EDRL) AS 'EDRL_MIN', SUM(CASE  WHEN t.EDRL IS NULL THEN 1 ELSE 0 END) AS 'EDRL_null_num' , MAX(t.EDDLDY) AS 'EDDLDY_MAX', MIN(t.EDDLDY) AS 'EDDLDY_MIN' , SUM(CASE  WHEN t.EDDLDY IS NULL THEN 1 ELSE 0 END) AS 'EDDLDY_null_num', MAX(t.FZSHGYZY) AS 'FZSHGYZY_MAX' , MIN(t.FZSHGYZY) AS 'FZSHGYZY_MIN', SUM(CASE  WHEN t.FZSHGYZY IS NULL THEN 1 ELSE 0 END) AS 'FZSHGYZY_null_num' , MAX(t.DLZKGYZY) AS 'DLZKGYZY_MAX', MIN(t.DLZKGYZY) AS 'DLZKGYZY_MIN' , SUM(CASE  WHEN t.DLZKGYZY IS NULL THEN 1 ELSE 0 END) AS 'DLZKGYZY_null_num', MAX(t.DLZKZYDY) AS 'DLZKZYDY_MAX' , MIN(t.DLZKZYDY) AS 'DLZKZYDY_MIN', SUM(CASE  WHEN t.DLZKZYDY IS NULL THEN 1 ELSE 0 END) AS 'DLZKZYDY_null_num' , MAX(t.KZSH) AS 'KZSH_MAX', MIN(t.KZSH) AS 'KZSH_MIN' , SUM(CASE  WHEN t.KZSH IS NULL THEN 1 ELSE 0 END) AS 'KZSH_null_num', MAX(t.ZZ) AS 'ZZ_MAX' , MIN(t.ZZ) AS 'ZZ_MIN', SUM(CASE  WHEN t.ZZ IS NULL THEN 1 ELSE 0 END) AS 'ZZ_null_num' , MAX(t.YZ) AS 'YZ_MAX', MIN(t.YZ) AS 'YZ_MIN' , SUM(CASE  WHEN t.YZ IS NULL THEN 1 ELSE 0 END) AS 'YZ_null_num', MAX(t.SF6QTEDYL) AS 'SF6QTEDYL_MAX' , MIN(t.SF6QTEDYL) AS 'SF6QTEDYL_MIN', SUM(CASE  WHEN t.SF6QTEDYL IS NULL THEN 1 ELSE 0 END) AS 'SF6QTEDYL_null_num' , MAX(t.QSZ) AS 'QSZ_MAX', MIN(t.QSZ) AS 'QSZ_MIN' , SUM(CASE  WHEN t.QSZ IS NULL THEN 1 ELSE 0 END) AS 'QSZ_null_num', MAX(t.QPFLZS) AS 'QPFLZS_MAX' , MIN(t.QPFLZS) AS 'QPFLZS_MIN', SUM(CASE  WHEN t.QPFLZS IS NULL THEN 1 ELSE 0 END) AS 'QPFLZS_null_num' , MAX(t.SJYXZ) AS 'SJYXZ_MAX', MIN(t.SJYXZ) AS 'SJYXZ_MIN' , SUM(CASE  WHEN t.SJYXZ IS NULL THEN 1 ELSE 0 END) AS 'SJYXZ_null_num', MAX(t.SF6QZBT) AS 'SF6QZBT_MAX' , MIN(t.SF6QZBT) AS 'SF6QZBT_MIN', SUM(CASE  WHEN t.SF6QZBT IS NULL THEN 1 ELSE 0 END) AS 'SF6QZBT_null_num' , MAX(t.SF6QZYZKG) AS 'SF6QZYZKG_MAX', MIN(t.SF6QZYZKG) AS 'SF6QZYZKG_MIN' , SUM(CASE  WHEN t.SF6QZYZKG IS NULL THEN 1 ELSE 0 END) AS 'SF6QZYZKG_null_num', MAX(t.SF6QTYLDLC) AS 'SF6QTYLDLC_MAX' , MIN(t.SF6QTYLDLC) AS 'SF6QTYLDLC_MIN', SUM(CASE  WHEN t.SF6QTYLDLC IS NULL THEN 1 ELSE 0 END) AS 'SF6QTYLDLC_null_num' , MAX(t.LQSZ) AS 'LQSZ_MAX', MIN(t.LQSZ) AS 'LQSZ_MIN' , SUM(CASE  WHEN t.LQSZ IS NULL THEN 1 ELSE 0 END) AS 'LQSZ_null_num', MAX(t.ZSSP) AS 'ZSSP_MAX' , MIN(t.ZSSP) AS 'ZSSP_MIN', SUM(CASE  WHEN t.ZSSP IS NULL THEN 1 ELSE 0 END) AS 'ZSSP_null_num' FROM t_sb_znyc_zbyq t LEFT JOIN t_dw_bzzx_sccj t1 ON t.SCCJ = t1.SCCJBM GROUP BY t.sccj, t.xh";
		sqlNameMap.put(sql_sb_zbyq, "主变压器");
		String sql_sb_blq = "SELECT t.SCCJ AS 'sccj', t1.SCCJMC AS 'sccjmc', t.XH AS 'xh', MAX(t.EDPL) AS 'EDPL_MAX' , MIN(t.EDPL) AS 'EDPL_MIN', SUM(CASE  WHEN t.EDPL IS NULL THEN 1 ELSE 0 END) AS 'EDPL_null_num' , MAX(t.CXYXDY) AS 'CXYXDY_MAX', MIN(t.CXYXDY) AS 'CXYXDY_MIN' , SUM(CASE  WHEN t.CXYXDY IS NULL THEN 1 ELSE 0 END) AS 'CXYXDY_null_num', MAX(t.GPCKDY) AS 'GPCKDY_MAX' , MIN(t.GPCKDY) AS 'GPCKDY_MIN', SUM(CASE  WHEN t.GPCKDY IS NULL THEN 1 ELSE 0 END) AS 'GPCKDY_null_num' , MAX(t.BCFDDL) AS 'BCFDDL_MAX', MIN(t.BCFDDL) AS 'BCFDDL_MIN' , SUM(CASE  WHEN t.BCFDDL IS NULL THEN 1 ELSE 0 END) AS 'BCFDDL_null_num', MAX(t.PDBJ) AS 'PDBJ_MAX' , MIN(t.PDBJ) AS 'PDBJ_MIN', SUM(CASE  WHEN t.PDBJ IS NULL THEN 1 ELSE 0 END) AS 'PDBJ_null_num' , MAX(t.ZLCKDY) AS 'ZLCKDY_MAX', MIN(t.ZLCKDY) AS 'ZLCKDY_MIN' , SUM(CASE  WHEN t.ZLCKDY IS NULL THEN 1 ELSE 0 END) AS 'ZLCKDY_null_num', MAX(t.DBCJDLXCY) AS 'DBCJDLXCY_MAX' , MIN(t.DBCJDLXCY) AS 'DBCJDLXCY_MIN', SUM(CASE  WHEN t.DBCJDLXCY IS NULL THEN 1 ELSE 0 END) AS 'DBCJDLXCY_null_num' , MAX(t.QDLCSZYXDY) AS 'QDLCSZYXDY_MAX', MIN(t.QDLCSZYXDY) AS 'QDLCSZYXDY_MIN' , SUM(CASE  WHEN t.QDLCSZYXDY IS NULL THEN 1 ELSE 0 END) AS 'QDLCSZYXDY_null_num', MAX(t.DDLCJDLZ) AS 'DDLCJDLZ_MAX' , MIN(t.DDLCJDLZ) AS 'DDLCJDLZ_MIN', SUM(CASE  WHEN t.DDLCJDLZ IS NULL THEN 1 ELSE 0 END) AS 'DDLCJDLZ_null_num' , MAX(t.YLSFDL) AS 'YLSFDL_MAX', MIN(t.YLSFDL) AS 'YLSFDL_MIN' , SUM(CASE  WHEN t.YLSFDL IS NULL THEN 1 ELSE 0 END) AS 'YLSFDL_null_num', MAX(t.FBTLRL) AS 'FBTLRL_MAX' , MIN(t.FBTLRL) AS 'FBTLRL_MIN', SUM(CASE  WHEN t.FBTLRL IS NULL THEN 1 ELSE 0 END) AS 'FBTLRL_null_num' , MAX(t.CXYXDL) AS 'CXYXDL_MAX', MIN(t.CXYXDL) AS 'CXYXDL_MIN' , SUM(CASE  WHEN t.CXYXDL IS NULL THEN 1 ELSE 0 END) AS 'CXYXDL_null_num', MAX(t.GPFDDY) AS 'GPFDDY_MAX' , MIN(t.GPFDDY) AS 'GPFDDY_MIN', SUM(CASE  WHEN t.GPFDDY IS NULL THEN 1 ELSE 0 END) AS 'GPFDDY_null_num' , MAX(t.LDCJCYFZ) AS 'LDCJCYFZ_MAX', MIN(t.LDCJCYFZ) AS 'LDCJCYFZ_MIN' , SUM(CASE  WHEN t.LDCJCYFZ IS NULL THEN 1 ELSE 0 END) AS 'LDCJCYFZ_null_num', MAX(t.MXJS) AS 'MXJS_MAX' , MIN(t.MXJS) AS 'MXJS_MIN', SUM(CASE  WHEN t.MXJS IS NULL THEN 1 ELSE 0 END) AS 'MXJS_null_num' , MAX(t.CZCJDLXCY) AS 'CZCJDLXCY_MAX', MIN(t.CZCJDLXCY) AS 'CZCJDLXCY_MIN' , SUM(CASE  WHEN t.CZCJDLXCY IS NULL THEN 1 ELSE 0 END) AS 'CZCJDLXCY_null_num', MAX(t.ZXDLCSZYXDY) AS 'ZXDLCSZYXDY_MAX' , MIN(t.ZXDLCSZYXDY) AS 'ZXDLCSZYXDY_MIN', SUM(CASE  WHEN t.ZXDLCSZYXDY IS NULL THEN 1 ELSE 0 END) AS 'ZXDLCSZYXDY_null_num' , MAX(t.DXFBCJDLZ) AS 'DXFBCJDLZ_MAX', MIN(t.DXFBCJDLZ) AS 'DXFBCJDLZ_MIN' , SUM(CASE  WHEN t.DXFBCJDLZ IS NULL THEN 1 ELSE 0 END) AS 'DXFBCJDLZ_null_num', MAX(t.JYDZCSZ) AS 'JYDZCSZ_MAX' , MIN(t.JYDZCSZ) AS 'JYDZCSZ_MIN', SUM(CASE  WHEN t.JYDZCSZ IS NULL THEN 1 ELSE 0 END) AS 'JYDZCSZ_null_num' , MAX(t.GD) AS 'GD_MAX', MIN(t.GD) AS 'GD_MIN' , SUM(CASE  WHEN t.GD IS NULL THEN 1 ELSE 0 END) AS 'GD_null_num' FROM t_sb_znyc_blq t LEFT JOIN t_dw_bzzx_sccj t1 ON t.SCCJ = t1.SCCJBM GROUP BY t.sccj, t.xh";
		sqlNameMap.put(sql_sb_blq, "避雷器");
		String sql_sb_dkq = "SELECT t.SCCJ AS 'sccj', t1.SCCJMC AS 'sccjmc', t.XH AS 'xh', MAX(t.EDPL) AS 'EDPL_MAX' , MIN(t.EDPL) AS 'EDPL_MIN', SUM(CASE  WHEN t.EDPL IS NULL THEN 1 ELSE 0 END) AS 'EDPL_null_num' , MAX(t.EDDK) AS 'EDDK_MAX', MIN(t.EDDK) AS 'EDDK_MIN' , SUM(CASE  WHEN t.EDDK IS NULL THEN 1 ELSE 0 END) AS 'EDDK_null_num', MAX(t.EDDG) AS 'EDDG_MAX' , MIN(t.EDDG) AS 'EDDG_MIN', SUM(CASE  WHEN t.EDDG IS NULL THEN 1 ELSE 0 END) AS 'EDDG_null_num' , MAX(t.EDSH) AS 'EDSH_MAX', MIN(t.EDSH) AS 'EDSH_MIN' , SUM(CASE  WHEN t.EDSH IS NULL THEN 1 ELSE 0 END) AS 'EDSH_null_num', MAX(t.EDDSNSDL) AS 'EDDSNSDL_MAX' , MIN(t.EDDSNSDL) AS 'EDDSNSDL_MIN', SUM(CASE  WHEN t.EDDSNSDL IS NULL THEN 1 ELSE 0 END) AS 'EDDSNSDL_null_num' , MAX(t.EDDLCXSJ) AS 'EDDLCXSJ_MAX', MIN(t.EDDLCXSJ) AS 'EDDLCXSJ_MIN' , SUM(CASE  WHEN t.EDDLCXSJ IS NULL THEN 1 ELSE 0 END) AS 'EDDLCXSJ_null_num', MAX(t.QSZ) AS 'QSZ_MAX' , MIN(t.QSZ) AS 'QSZ_MIN', SUM(CASE  WHEN t.QSZ IS NULL THEN 1 ELSE 0 END) AS 'QSZ_null_num' , MAX(t.LXDK) AS 'LXDK_MAX', MIN(t.LXDK) AS 'LXDK_MIN' , SUM(CASE  WHEN t.LXDK IS NULL THEN 1 ELSE 0 END) AS 'LXDK_null_num', MAX(t.YZ) AS 'YZ_MAX' , MIN(t.YZ) AS 'YZ_MIN', SUM(CASE  WHEN t.YZ IS NULL THEN 1 ELSE 0 END) AS 'YZ_null_num' , MAX(t.EDDL) AS 'EDDL_MAX', MIN(t.EDDL) AS 'EDDL_MIN' , SUM(CASE  WHEN t.EDDL IS NULL THEN 1 ELSE 0 END) AS 'EDDL_null_num', MAX(t.EDRL) AS 'EDRL_MAX' , MIN(t.EDRL) AS 'EDRL_MIN', SUM(CASE  WHEN t.EDRL IS NULL THEN 1 ELSE 0 END) AS 'EDRL_null_num' , MAX(t.EDDKL) AS 'EDDKL_MAX', MIN(t.EDDKL) AS 'EDDKL_MIN' , SUM(CASE  WHEN t.EDDKL IS NULL THEN 1 ELSE 0 END) AS 'EDDKL_null_num', MAX(t.ZZ) AS 'ZZ_MAX' , MIN(t.ZZ) AS 'ZZ_MIN', SUM(CASE  WHEN t.ZZ IS NULL THEN 1 ELSE 0 END) AS 'ZZ_null_num' , MAX(t.BFZK) AS 'BFZK_MAX', MIN(t.BFZK) AS 'BFZK_MIN' , SUM(CASE  WHEN t.BFZK IS NULL THEN 1 ELSE 0 END) AS 'BFZK_null_num', MAX(t.EDFZNSDL) AS 'EDFZNSDL_MAX' , MIN(t.EDFZNSDL) AS 'EDFZNSDL_MIN', SUM(CASE  WHEN t.EDFZNSDL IS NULL THEN 1 ELSE 0 END) AS 'EDFZNSDL_null_num' , MAX(t.LXYXDGDYBS) AS 'LXYXDGDYBS_MAX', MIN(t.LXYXDGDYBS) AS 'LXYXDGDYBS_MIN' , SUM(CASE  WHEN t.LXYXDGDYBS IS NULL THEN 1 ELSE 0 END) AS 'LXYXDGDYBS_null_num', MAX(t.LXYXDGDLBS) AS 'LXYXDGDLBS_MAX' , MIN(t.LXYXDGDLBS) AS 'LXYXDGDLBS_MIN', SUM(CASE  WHEN t.LXYXDGDLBS IS NULL THEN 1 ELSE 0 END) AS 'LXYXDGDLBS_null_num' FROM t_sb_znyc_dkq t LEFT JOIN t_dw_bzzx_sccj t1 ON t.SCCJ = t1.SCCJBM GROUP BY t.sccj, t.xh";
		sqlNameMap.put(sql_sb_dkq, "电抗器");
		String sql_sb_dldrq = "SELECT t.SCCJ AS 'sccj', t1.SCCJMC AS 'sccjmc', t.XH AS 'xh', MAX(t.DTRL) AS 'DTRL_MAX' , MIN(t.DTRL) AS 'DTRL_MIN', SUM(CASE  WHEN t.DTRL IS NULL THEN 1 ELSE 0 END) AS 'DTRL_null_num' , MAX(t.DRZ) AS 'DRZ_MAX', MIN(t.DRZ) AS 'DRZ_MIN' , SUM(CASE  WHEN t.DRZ IS NULL THEN 1 ELSE 0 END) AS 'DRZ_null_num', MAX(t.EDPL) AS 'EDPL_MAX' , MIN(t.EDPL) AS 'EDPL_MIN', SUM(CASE  WHEN t.EDPL IS NULL THEN 1 ELSE 0 END) AS 'EDPL_null_num' , MAX(t.ZZRL) AS 'ZZRL_MAX', MIN(t.ZZRL) AS 'ZZRL_MIN' , SUM(CASE  WHEN t.ZZRL IS NULL THEN 1 ELSE 0 END) AS 'ZZRL_null_num', MAX(t.TS) AS 'TS_MAX' , MIN(t.TS) AS 'TS_MIN', SUM(CASE  WHEN t.TS IS NULL THEN 1 ELSE 0 END) AS 'TS_null_num' FROM t_sb_znyc_dldrq t LEFT JOIN t_dw_bzzx_sccj t1 ON t.SCCJ = t1.SCCJBM GROUP BY t.sccj, t.xh";
		sqlNameMap.put(sql_sb_dldrq, "电力电容器");
		String sql_sb_dlhgq = "SELECT t.SCCJ AS 'sccj', t1.SCCJMC AS 'sccjmc', t.XH AS 'xh', MAX(t.EDPL) AS 'EDPL_MAX' , MIN(t.EDPL) AS 'EDPL_MIN', SUM(CASE  WHEN t.EDPL IS NULL THEN 1 ELSE 0 END) AS 'EDPL_null_num' , MAX(t.ECRZZSL) AS 'ECRZZSL_MAX', MIN(t.ECRZZSL) AS 'ECRZZSL_MIN' , SUM(CASE  WHEN t.ECRZZSL IS NULL THEN 1 ELSE 0 END) AS 'ECRZZSL_null_num', MAX(t.SF6QTEDYL) AS 'SF6QTEDYL_MAX' , MIN(t.SF6QTEDYL) AS 'SF6QTEDYL_MIN', SUM(CASE  WHEN t.SF6QTEDYL IS NULL THEN 1 ELSE 0 END) AS 'SF6QTEDYL_null_num' , MAX(t.SF6QTBJYL) AS 'SF6QTBJYL_MAX', MIN(t.SF6QTBJYL) AS 'SF6QTBJYL_MIN' , SUM(CASE  WHEN t.SF6QTBJYL IS NULL THEN 1 ELSE 0 END) AS 'SF6QTBJYL_null_num', MAX(t.SF6QTYSYL) AS 'SF6QTYSYL_MAX' , MIN(t.SF6QTYSYL) AS 'SF6QTYSYL_MIN', SUM(CASE  WHEN t.SF6QTYSYL IS NULL THEN 1 ELSE 0 END) AS 'SF6QTYSYL_null_num' , MAX(t.LXRWDDL) AS 'LXRWDDL_MAX', MIN(t.LXRWDDL) AS 'LXRWDDL_MIN' , SUM(CASE  WHEN t.LXRWDDL IS NULL THEN 1 ELSE 0 END) AS 'LXRWDDL_null_num', MAX(t.ECRZSLCL) AS 'ECRZSLCL_MAX' , MIN(t.ECRZSLCL) AS 'ECRZSLCL_MIN', SUM(CASE  WHEN t.ECRZSLCL IS NULL THEN 1 ELSE 0 END) AS 'ECRZSLCL_null_num' , MAX(t.ECRZSLZTBH) AS 'ECRZSLZTBH_MAX', MIN(t.ECRZSLZTBH) AS 'ECRZSLZTBH_MIN' , SUM(CASE  WHEN t.ECRZSLZTBH IS NULL THEN 1 ELSE 0 END) AS 'ECRZSLZTBH_null_num', MAX(t.YZ) AS 'YZ_MAX' , MIN(t.YZ) AS 'YZ_MIN', SUM(CASE  WHEN t.YZ IS NULL THEN 1 ELSE 0 END) AS 'YZ_null_num' , MAX(t.EDSCRLCL) AS 'EDSCRLCL_MAX', MIN(t.EDSCRLCL) AS 'EDSCRLCL_MIN' , SUM(CASE  WHEN t.EDSCRLCL IS NULL THEN 1 ELSE 0 END) AS 'EDSCRLCL_null_num', MAX(t.EDSCRLZTBH) AS 'EDSCRLZTBH_MAX' , MIN(t.EDSCRLZTBH) AS 'EDSCRLZTBH_MIN', SUM(CASE  WHEN t.EDSCRLZTBH IS NULL THEN 1 ELSE 0 END) AS 'EDSCRLZTBH_null_num' , MAX(t.ZDCXDL) AS 'ZDCXDL_MAX', MIN(t.ZDCXDL) AS 'ZDCXDL_MIN' , SUM(CASE  WHEN t.ZDCXDL IS NULL THEN 1 ELSE 0 END) AS 'ZDCXDL_null_num', MAX(t.CZCJDY) AS 'CZCJDY_MAX' , MIN(t.CZCJDY) AS 'CZCJDY_MIN', SUM(CASE  WHEN t.CZCJDY IS NULL THEN 1 ELSE 0 END) AS 'CZCJDY_null_num' , MAX(t.PDJL) AS 'PDJL_MAX', MIN(t.PDJL) AS 'PDJL_MIN' , SUM(CASE  WHEN t.PDJL IS NULL THEN 1 ELSE 0 END) AS 'PDJL_null_num', MAX(t.LDCJNYFZ) AS 'LDCJNYFZ_MAX' , MIN(t.LDCJNYFZ) AS 'LDCJNYFZ_MIN', SUM(CASE  WHEN t.LDCJNYFZ IS NULL THEN 1 ELSE 0 END) AS 'LDCJNYFZ_null_num' , MAX(t.CZCJNYFZST) AS 'CZCJNYFZST_MAX', MIN(t.CZCJNYFZST) AS 'CZCJNYFZST_MIN' , SUM(CASE  WHEN t.CZCJNYFZST IS NULL THEN 1 ELSE 0 END) AS 'CZCJNYFZST_null_num', MAX(t.KSZTDL) AS 'KSZTDL_MAX' , MIN(t.KSZTDL) AS 'KSZTDL_MIN', SUM(CASE  WHEN t.KSZTDL IS NULL THEN 1 ELSE 0 END) AS 'KSZTDL_null_num' , MAX(t.ZLDLCLJD) AS 'ZLDLCLJD_MAX', MIN(t.ZLDLCLJD) AS 'ZLDLCLJD_MIN' , SUM(CASE  WHEN t.ZLDLCLJD IS NULL THEN 1 ELSE 0 END) AS 'ZLDLCLJD_null_num', MAX(t.XBDLCLJD) AS 'XBDLCLJD_MAX' , MIN(t.XBDLCLJD) AS 'XBDLCLJD_MIN', SUM(CASE  WHEN t.XBDLCLJD IS NULL THEN 1 ELSE 0 END) AS 'XBDLCLJD_null_num' , MAX(t.EDYCDL) AS 'EDYCDL_MAX', MIN(t.EDYCDL) AS 'EDYCDL_MIN' , SUM(CASE  WHEN t.EDYCDL IS NULL THEN 1 ELSE 0 END) AS 'EDYCDL_null_num', MAX(t.EDDSRDL) AS 'EDDSRDL_MAX' , MIN(t.EDDSRDL) AS 'EDDSRDL_MIN', SUM(CASE  WHEN t.EDDSRDL IS NULL THEN 1 ELSE 0 END) AS 'EDDSRDL_null_num' , MAX(t.EDSYSJ) AS 'EDSYSJ_MAX', MIN(t.EDSYSJ) AS 'EDSYSJ_MIN' , SUM(CASE  WHEN t.EDSYSJ IS NULL THEN 1 ELSE 0 END) AS 'EDSYSJ_null_num', MAX(t.EDDL) AS 'EDDL_MAX' , MIN(t.EDDL) AS 'EDDL_MIN', SUM(CASE  WHEN t.EDDL IS NULL THEN 1 ELSE 0 END) AS 'EDDL_null_num' , MAX(t.DWDDL) AS 'DWDDL_MAX', MIN(t.DWDDL) AS 'DWDDL_MIN' , SUM(CASE  WHEN t.DWDDL IS NULL THEN 1 ELSE 0 END) AS 'DWDDL_null_num', MAX(t.RWDDL) AS 'RWDDL_MAX' , MIN(t.RWDDL) AS 'RWDDL_MIN', SUM(CASE  WHEN t.RWDDL IS NULL THEN 1 ELSE 0 END) AS 'RWDDL_null_num' , MAX(t.PDBJ) AS 'PDBJ_MAX', MIN(t.PDBJ) AS 'PDBJ_MIN' , SUM(CASE  WHEN t.PDBJ IS NULL THEN 1 ELSE 0 END) AS 'PDBJ_null_num', MAX(t.SF6QTZXYXYL) AS 'SF6QTZXYXYL_MAX' , MIN(t.SF6QTZXYXYL) AS 'SF6QTZXYXYL_MIN', SUM(CASE  WHEN t.SF6QTZXYXYL IS NULL THEN 1 ELSE 0 END) AS 'SF6QTZXYXYL_null_num' , MAX(t.SF6QTZL) AS 'SF6QTZL_MAX', MIN(t.SF6QTZL) AS 'SF6QTZL_MIN' , SUM(CASE  WHEN t.SF6QTZL IS NULL THEN 1 ELSE 0 END) AS 'SF6QTZL_null_num', MAX(t.RWDDLSJ) AS 'RWDDLSJ_MAX' , MIN(t.RWDDLSJ) AS 'RWDDLSJ_MIN', SUM(CASE  WHEN t.RWDDLSJ IS NULL THEN 1 ELSE 0 END) AS 'RWDDLSJ_null_num' , MAX(t.ECRZSLBH) AS 'ECRZSLBH_MAX', MIN(t.ECRZSLBH) AS 'ECRZSLBH_MIN' , SUM(CASE  WHEN t.ECRZSLBH IS NULL THEN 1 ELSE 0 END) AS 'ECRZSLBH_null_num', MAX(t.YZ) AS 'YZ_MAX' , MIN(t.YZ) AS 'YZ_MIN', SUM(CASE  WHEN t.YZ IS NULL THEN 1 ELSE 0 END) AS 'YZ_null_num' , MAX(t.GD) AS 'GD_MAX', MIN(t.GD) AS 'GD_MIN' , SUM(CASE  WHEN t.GD IS NULL THEN 1 ELSE 0 END) AS 'GD_null_num', MAX(t.EDSCRLBH) AS 'EDSCRLBH_MAX' , MIN(t.EDSCRLBH) AS 'EDSCRLBH_MIN', SUM(CASE  WHEN t.EDSCRLBH IS NULL THEN 1 ELSE 0 END) AS 'EDSCRLBH_null_num' , MAX(t.BMJYDYDJ) AS 'BMJYDYDJ_MAX', MIN(t.BMJYDYDJ) AS 'BMJYDYDJ_MIN' , SUM(CASE  WHEN t.BMJYDYDJ IS NULL THEN 1 ELSE 0 END) AS 'BMJYDYDJ_null_num', MAX(t.LDCJDY) AS 'LDCJDY_MAX' , MIN(t.LDCJDY) AS 'LDCJDY_MIN', SUM(CASE  WHEN t.LDCJDY IS NULL THEN 1 ELSE 0 END) AS 'LDCJDY_null_num' , MAX(t.DSNSDL) AS 'DSNSDL_MAX', MIN(t.DSNSDL) AS 'DSNSDL_MIN' , SUM(CASE  WHEN t.DSNSDL IS NULL THEN 1 ELSE 0 END) AS 'DSNSDL_null_num', MAX(t.ZDCXDY) AS 'ZDCXDY_MAX' , MIN(t.ZDCXDY) AS 'ZDCXDY_MIN', SUM(CASE  WHEN t.ZDCXDY IS NULL THEN 1 ELSE 0 END) AS 'ZDCXDY_null_num' , MAX(t.DSRDL) AS 'DSRDL_MAX', MIN(t.DSRDL) AS 'DSRDL_MIN' , SUM(CASE  WHEN t.DSRDL IS NULL THEN 1 ELSE 0 END) AS 'DSRDL_null_num', MAX(t.ZLNY) AS 'ZLNY_MAX' , MIN(t.ZLNY) AS 'ZLNY_MIN', SUM(CASE  WHEN t.ZLNY IS NULL THEN 1 ELSE 0 END) AS 'ZLNY_null_num' , MAX(t.JBFDSYDY) AS 'JBFDSYDY_MAX', MIN(t.JBFDSYDY) AS 'JBFDSYDY_MIN' , SUM(CASE  WHEN t.JBFDSYDY IS NULL THEN 1 ELSE 0 END) AS 'JBFDSYDY_null_num', MAX(t.WXDGRSYDY) AS 'WXDGRSYDY_MAX' , MIN(t.WXDGRSYDY) AS 'WXDGRSYDY_MIN', SUM(CASE  WHEN t.WXDGRSYDY IS NULL THEN 1 ELSE 0 END) AS 'WXDGRSYDY_null_num' , MAX(t.JYXY1090) AS 'JYXY1090_MAX', MIN(t.JYXY1090) AS 'JYXY1090_MIN' , SUM(CASE  WHEN t.JYXY1090 IS NULL THEN 1 ELSE 0 END) AS 'JYXY1090_null_num', MAX(t.EDKDYCDLXS) AS 'EDKDYCDLXS_MAX' , MIN(t.EDKDYCDLXS) AS 'EDKDYCDLXS_MIN', SUM(CASE  WHEN t.EDKDYCDLXS IS NULL THEN 1 ELSE 0 END) AS 'EDKDYCDLXS_null_num' , MAX(t.EDECSC) AS 'EDECSC_MAX', MIN(t.EDECSC) AS 'EDECSC_MIN' , SUM(CASE  WHEN t.EDECSC IS NULL THEN 1 ELSE 0 END) AS 'EDECSC_null_num' FROM t_sb_znyc_dlhgq t LEFT JOIN t_dw_bzzx_sccj t1 ON t.SCCJ = t1.SCCJBM GROUP BY t.sccj, t.xh";
		sqlNameMap.put(sql_sb_dlhgq, "电流互感器");
		String sql_sb_dyhgq = "SELECT t.SCCJ AS 'sccj', t1.SCCJMC AS 'sccjmc', t.XH AS 'xh', MAX(t.ECRZZSL) AS 'ECRZZSL_MAX' , MIN(t.ECRZZSL) AS 'ECRZZSL_MIN', SUM(CASE  WHEN t.ECRZZSL IS NULL THEN 1 ELSE 0 END) AS 'ECRZZSL_null_num' , MAX(t.ZEDDRL) AS 'ZEDDRL_MAX', MIN(t.ZEDDRL) AS 'ZEDDRL_MIN' , SUM(CASE  WHEN t.ZEDDRL IS NULL THEN 1 ELSE 0 END) AS 'ZEDDRL_null_num', MAX(t.SJDRL) AS 'SJDRL_MAX' , MIN(t.SJDRL) AS 'SJDRL_MIN', SUM(CASE  WHEN t.SJDRL IS NULL THEN 1 ELSE 0 END) AS 'SJDRL_null_num' , MAX(t.XJC1DRL) AS 'XJC1DRL_MAX', MIN(t.XJC1DRL) AS 'XJC1DRL_MIN' , SUM(CASE  WHEN t.XJC1DRL IS NULL THEN 1 ELSE 0 END) AS 'XJC1DRL_null_num', MAX(t.SF6QTBJYL) AS 'SF6QTBJYL_MAX' , MIN(t.SF6QTBJYL) AS 'SF6QTBJYL_MIN', SUM(CASE  WHEN t.SF6QTBJYL IS NULL THEN 1 ELSE 0 END) AS 'SF6QTBJYL_null_num' , MAX(t.ECRZSLBH) AS 'ECRZSLBH_MAX', MIN(t.ECRZSLBH) AS 'ECRZSLBH_MIN' , SUM(CASE  WHEN t.ECRZSLBH IS NULL THEN 1 ELSE 0 END) AS 'ECRZSLBH_null_num', MAX(t.GD) AS 'GD_MAX' , MIN(t.GD) AS 'GD_MIN', SUM(CASE  WHEN t.GD IS NULL THEN 1 ELSE 0 END) AS 'GD_null_num' , MAX(t.YZ) AS 'YZ_MAX', MIN(t.YZ) AS 'YZ_MIN' , SUM(CASE  WHEN t.YZ IS NULL THEN 1 ELSE 0 END) AS 'YZ_null_num', MAX(t.EDSCRLCL) AS 'EDSCRLCL_MAX' , MIN(t.EDSCRLCL) AS 'EDSCRLCL_MIN', SUM(CASE  WHEN t.EDSCRLCL IS NULL THEN 1 ELSE 0 END) AS 'EDSCRLCL_null_num' , MAX(t.EDPL) AS 'EDPL_MAX', MIN(t.EDPL) AS 'EDPL_MIN' , SUM(CASE  WHEN t.EDPL IS NULL THEN 1 ELSE 0 END) AS 'EDPL_null_num', MAX(t.PDBJ) AS 'PDBJ_MAX' , MIN(t.PDBJ) AS 'PDBJ_MIN', SUM(CASE  WHEN t.PDBJ IS NULL THEN 1 ELSE 0 END) AS 'PDBJ_null_num' , MAX(t.DRQJS) AS 'DRQJS_MAX', MIN(t.DRQJS) AS 'DRQJS_MIN' , SUM(CASE  WHEN t.DRQJS IS NULL THEN 1 ELSE 0 END) AS 'DRQJS_null_num', MAX(t.ZJDRL) AS 'ZJDRL_MAX' , MIN(t.ZJDRL) AS 'ZJDRL_MIN', SUM(CASE  WHEN t.ZJDRL IS NULL THEN 1 ELSE 0 END) AS 'ZJDRL_null_num' , MAX(t.XJC2DRL) AS 'XJC2DRL_MAX', MIN(t.XJC2DRL) AS 'XJC2DRL_MIN' , SUM(CASE  WHEN t.XJC2DRL IS NULL THEN 1 ELSE 0 END) AS 'XJC2DRL_null_num', MAX(t.SF6QTEDYL) AS 'SF6QTEDYL_MAX' , MIN(t.SF6QTEDYL) AS 'SF6QTEDYL_MIN', SUM(CASE  WHEN t.SF6QTEDYL IS NULL THEN 1 ELSE 0 END) AS 'SF6QTEDYL_null_num' , MAX(t.ECRZSLCL) AS 'ECRZSLCL_MAX', MIN(t.ECRZSLCL) AS 'ECRZSLCL_MIN' , SUM(CASE  WHEN t.ECRZSLCL IS NULL THEN 1 ELSE 0 END) AS 'ECRZSLCL_null_num', MAX(t.ZZ) AS 'ZZ_MAX' , MIN(t.ZZ) AS 'ZZ_MIN', SUM(CASE  WHEN t.ZZ IS NULL THEN 1 ELSE 0 END) AS 'ZZ_null_num' , MAX(t.EDKLZJDY) AS 'EDKLZJDY_MAX', MIN(t.EDKLZJDY) AS 'EDKLZJDY_MIN' , SUM(CASE  WHEN t.EDKLZJDY IS NULL THEN 1 ELSE 0 END) AS 'EDKLZJDY_null_num', MAX(t.SF6QTZL) AS 'SF6QTZL_MAX' , MIN(t.SF6QTZL) AS 'SF6QTZL_MIN', SUM(CASE  WHEN t.SF6QTZL IS NULL THEN 1 ELSE 0 END) AS 'SF6QTZL_null_num' , MAX(t.EDSCRLBH) AS 'EDSCRLBH_MAX', MIN(t.EDSCRLBH) AS 'EDSCRLBH_MIN' , SUM(CASE  WHEN t.EDSCRLBH IS NULL THEN 1 ELSE 0 END) AS 'EDSCRLBH_null_num' FROM t_sb_znyc_dyhgq t LEFT JOIN t_dw_bzzx_sccj t1 ON t.SCCJ = t1.SCCJBM GROUP BY t.sccj, t.xh";
		sqlNameMap.put(sql_sb_dyhgq, "电压互感器");
		String sql_sb_dlq = "SELECT t.SCCJ AS 'sccj', t1.SCCJMC AS 'sccjmc', t.XH AS 'xh', MAX(t.EDPL) AS 'EDPL_MAX' , MIN(t.EDPL) AS 'EDPL_MIN', SUM(CASE  WHEN t.EDPL IS NULL THEN 1 ELSE 0 END) AS 'EDPL_null_num' , MAX(t.EDDLGHDL) AS 'EDDLGHDL_MAX', MIN(t.EDDLGHDL) AS 'EDDLGHDL_MIN' , SUM(CASE  WHEN t.EDDLGHDL IS NULL THEN 1 ELSE 0 END) AS 'EDDLGHDL_null_num', MAX(t.RWDDL) AS 'RWDDL_MAX' , MIN(t.RWDDL) AS 'RWDDL_MIN', SUM(CASE  WHEN t.RWDDL IS NULL THEN 1 ELSE 0 END) AS 'RWDDL_null_num' , MAX(t.DKSL) AS 'DKSL_MAX', MIN(t.DKSL) AS 'DKSL_MIN' , SUM(CASE  WHEN t.DKSL IS NULL THEN 1 ELSE 0 END) AS 'DKSL_null_num', MAX(t.TGGHJL) AS 'TGGHJL_MAX' , MIN(t.TGGHJL) AS 'TGGHJL_MIN', SUM(CASE  WHEN t.TGGHJL IS NULL THEN 1 ELSE 0 END) AS 'TGGHJL_null_num' , MAX(t.JXSM) AS 'JXSM_MAX', MIN(t.JXSM) AS 'JXSM_MIN' , SUM(CASE  WHEN t.JXSM IS NULL THEN 1 ELSE 0 END) AS 'JXSM_null_num', MAX(t.SF6QTBJYL) AS 'SF6QTBJYL_MAX' , MIN(t.SF6QTBJYL) AS 'SF6QTBJYL_MIN', SUM(CASE  WHEN t.SF6QTBJYL IS NULL THEN 1 ELSE 0 END) AS 'SF6QTBJYL_null_num' , MAX(t.HZBSCZYL) AS 'HZBSCZYL_MAX', MIN(t.HZBSCZYL) AS 'HZBSCZYL_MIN' , SUM(CASE  WHEN t.HZBSCZYL IS NULL THEN 1 ELSE 0 END) AS 'HZBSCZYL_null_num', MAX(t.ZHZBSYL) AS 'ZHZBSYL_MAX' , MIN(t.ZHZBSYL) AS 'ZHZBSYL_MIN', SUM(CASE  WHEN t.ZHZBSYL IS NULL THEN 1 ELSE 0 END) AS 'ZHZBSYL_null_num' , MAX(t.SXFZBTQ) AS 'SXFZBTQ_MAX', MIN(t.SXFZBTQ) AS 'SXFZBTQ_MIN' , SUM(CASE  WHEN t.SXFZBTQ IS NULL THEN 1 ELSE 0 END) AS 'SXFZBTQ_null_num', MAX(t.TXFZBTQ) AS 'TXFZBTQ_MAX' , MIN(t.TXFZBTQ) AS 'TXFZBTQ_MIN', SUM(CASE  WHEN t.TXFZBTQ IS NULL THEN 1 ELSE 0 END) AS 'TXFZBTQ_null_num' , MAX(t.EDSBKDDL) AS 'EDSBKDDL_MAX', MIN(t.EDSBKDDL) AS 'EDSBKDDL_MIN' , SUM(CASE  WHEN t.EDSBKDDL IS NULL THEN 1 ELSE 0 END) AS 'EDSBKDDL_null_num', MAX(t.EDXLCDKDDL) AS 'EDXLCDKDDL_MAX' , MIN(t.EDXLCDKDDL) AS 'EDXLCDKDDL_MIN', SUM(CASE  WHEN t.EDXLCDKDDL IS NULL THEN 1 ELSE 0 END) AS 'EDXLCDKDDL_null_num' , MAX(t.EDLDCJNSDYDD) AS 'EDLDCJNSDYDD_MAX', MIN(t.EDLDCJNSDYDD) AS 'EDLDCJNSDYDD_MIN' , SUM(CASE  WHEN t.EDLDCJNSDYDD IS NULL THEN 1 ELSE 0 END) AS 'EDLDCJNSDYDD_null_num', MAX(t.EDLDCJNSDYDK) AS 'EDLDCJNSDYDK_MAX' , MIN(t.EDLDCJNSDYDK) AS 'EDLDCJNSDYDK_MIN', SUM(CASE  WHEN t.EDLDCJNSDYDK IS NULL THEN 1 ELSE 0 END) AS 'EDLDCJNSDYDK_null_num' , MAX(t.YFZGPNYXJ) AS 'YFZGPNYXJ_MAX', MIN(t.YFZGPNYXJ) AS 'YFZGPNYXJ_MIN' , SUM(CASE  WHEN t.YFZGPNYXJ IS NULL THEN 1 ELSE 0 END) AS 'YFZGPNYXJ_null_num', MAX(t.FZHLEDDYDY) AS 'FZHLEDDYDY_MAX' , MIN(t.FZHLEDDYDY) AS 'FZHLEDDYDY_MIN', SUM(CASE  WHEN t.FZHLEDDYDY IS NULL THEN 1 ELSE 0 END) AS 'FZHLEDDYDY_null_num' , MAX(t.CZJGEDCZDY) AS 'CZJGEDCZDY_MAX', MIN(t.CZJGEDCZDY) AS 'CZJGEDCZDY_MIN' , SUM(CASE  WHEN t.CZJGEDCZDY IS NULL THEN 1 ELSE 0 END) AS 'CZJGEDCZDY_null_num', MAX(t.SF6QTZL) AS 'SF6QTZL_MAX' , MIN(t.SF6QTZL) AS 'SF6QTZL_MIN', SUM(CASE  WHEN t.SF6QTZL IS NULL THEN 1 ELSE 0 END) AS 'SF6QTZL_null_num' , MAX(t.CNDJDY) AS 'CNDJDY_MAX', MIN(t.CNDJDY) AS 'CNDJDY_MIN' , SUM(CASE  WHEN t.CNDJDY IS NULL THEN 1 ELSE 0 END) AS 'CNDJDY_null_num', MAX(t.QDYL) AS 'QDYL_MAX' , MIN(t.QDYL) AS 'QDYL_MIN', SUM(CASE  WHEN t.QDYL IS NULL THEN 1 ELSE 0 END) AS 'QDYL_null_num' , MAX(t.HZJCBSCZYL) AS 'HZJCBSCZYL_MAX', MIN(t.HZJCBSCZYL) AS 'HZJCBSCZYL_MIN' , SUM(CASE  WHEN t.HZJCBSCZYL IS NULL THEN 1 ELSE 0 END) AS 'HZJCBSCZYL_null_num', MAX(t.ZHZBSJCCZYL) AS 'ZHZBSJCCZYL_MAX' , MIN(t.ZHZBSJCCZYL) AS 'ZHZBSJCCZYL_MIN', SUM(CASE  WHEN t.ZHZBSJCCZYL IS NULL THEN 1 ELSE 0 END) AS 'ZHZBSJCCZYL_null_num' , MAX(t.YCJDYL) AS 'YCJDYL_MAX', MIN(t.YCJDYL) AS 'YCJDYL_MIN' , SUM(CASE  WHEN t.YCJDYL IS NULL THEN 1 ELSE 0 END) AS 'YCJDYL_null_num', MAX(t.AQFDZFHYL) AS 'AQFDZFHYL_MAX' , MIN(t.AQFDZFHYL) AS 'AQFDZFHYL_MIN', SUM(CASE  WHEN t.AQFDZFHYL IS NULL THEN 1 ELSE 0 END) AS 'AQFDZFHYL_null_num' , MAX(t.EDDLKDDL) AS 'EDDLKDDL_MAX', MIN(t.EDDLKDDL) AS 'EDDLKDDL_MIN' , SUM(CASE  WHEN t.EDDLKDDL IS NULL THEN 1 ELSE 0 END) AS 'EDDLKDDL_null_num', MAX(t.EDGZYL) AS 'EDGZYL_MAX' , MIN(t.EDGZYL) AS 'EDGZYL_MIN', SUM(CASE  WHEN t.EDGZYL IS NULL THEN 1 ELSE 0 END) AS 'EDGZYL_null_num' , MAX(t.EDDL) AS 'EDDL_MAX', MIN(t.EDDL) AS 'EDDL_MIN' , SUM(CASE  WHEN t.EDDL IS NULL THEN 1 ELSE 0 END) AS 'EDDL_null_num', MAX(t.EDDLDLKDCS) AS 'EDDLDLKDCS_MAX' , MIN(t.EDDLDLKDCS) AS 'EDDLDLKDCS_MIN', SUM(CASE  WHEN t.EDDLDLKDCS IS NULL THEN 1 ELSE 0 END) AS 'EDDLDLKDCS_null_num' , MAX(t.DWDDL) AS 'DWDDL_MAX', MIN(t.DWDDL) AS 'DWDDL_MIN' , SUM(CASE  WHEN t.DWDDL IS NULL THEN 1 ELSE 0 END) AS 'DWDDL_null_num', MAX(t.TGPDJL) AS 'TGPDJL_MAX' , MIN(t.TGPDJL) AS 'TGPDJL_MIN', SUM(CASE  WHEN t.TGPDJL IS NULL THEN 1 ELSE 0 END) AS 'TGPDJL_null_num' , MAX(t.DDXLBJ) AS 'DDXLBJ_MAX', MIN(t.DDXLBJ) AS 'DDXLBJ_MIN' , SUM(CASE  WHEN t.DDXLBJ IS NULL THEN 1 ELSE 0 END) AS 'DDXLBJ_null_num', MAX(t.HZDZ) AS 'HZDZ_MAX' , MIN(t.HZDZ) AS 'HZDZ_MIN', SUM(CASE  WHEN t.HZDZ IS NULL THEN 1 ELSE 0 END) AS 'HZDZ_null_num' , MAX(t.SF6QTEDYL) AS 'SF6QTEDYL_MAX', MIN(t.SF6QTEDYL) AS 'SF6QTEDYL_MIN' , SUM(CASE  WHEN t.SF6QTEDYL IS NULL THEN 1 ELSE 0 END) AS 'SF6QTEDYL_null_num', MAX(t.SF6QTBSYL) AS 'SF6QTBSYL_MAX' , MIN(t.SF6QTBSYL) AS 'SF6QTBSYL_MIN', SUM(CASE  WHEN t.SF6QTBSYL IS NULL THEN 1 ELSE 0 END) AS 'SF6QTBSYL_null_num' , MAX(t.FZBSCZYL) AS 'FZBSCZYL_MAX', MIN(t.FZBSCZYL) AS 'FZBSCZYL_MIN' , SUM(CASE  WHEN t.FZBSCZYL IS NULL THEN 1 ELSE 0 END) AS 'FZBSCZYL_null_num', MAX(t.ZDYXTZCS) AS 'ZDYXTZCS_MAX' , MIN(t.ZDYXTZCS) AS 'ZDYXTZCS_MIN', SUM(CASE  WHEN t.ZDYXTZCS IS NULL THEN 1 ELSE 0 END) AS 'ZDYXTZCS_null_num' , MAX(t.SXHZBTQ) AS 'SXHZBTQ_MAX', MIN(t.SXHZBTQ) AS 'SXHZBTQ_MIN' , SUM(CASE  WHEN t.SXHZBTQ IS NULL THEN 1 ELSE 0 END) AS 'SXHZBTQ_null_num', MAX(t.TXHZBTQ) AS 'TXHZBTQ_MAX' , MIN(t.TXHZBTQ) AS 'TXHZBTQ_MIN', SUM(CASE  WHEN t.TXHZBTQ IS NULL THEN 1 ELSE 0 END) AS 'TXHZBTQ_null_num' , MAX(t.JQGZKDDL) AS 'JQGZKDDL_MAX', MIN(t.JQGZKDDL) AS 'JQGZKDDL_MIN' , SUM(CASE  WHEN t.JQGZKDDL IS NULL THEN 1 ELSE 0 END) AS 'JQGZKDDL_null_num', MAX(t.EDDLCDKDDL) AS 'EDDLCDKDDL_MAX' , MIN(t.EDDLCDKDDL) AS 'EDDLCDKDDL_MIN', SUM(CASE  WHEN t.EDDLCDKDDL IS NULL THEN 1 ELSE 0 END) AS 'EDDLCDKDDL_null_num' , MAX(t.EDLDCJNSDYXJ) AS 'EDLDCJNSDYXJ_MAX', MIN(t.EDLDCJNSDYXJ) AS 'EDLDCJNSDYXJ_MIN' , SUM(CASE  WHEN t.EDLDCJNSDYXJ IS NULL THEN 1 ELSE 0 END) AS 'EDLDCJNSDYXJ_null_num', MAX(t.YFZGPNYDD) AS 'YFZGPNYDD_MAX' , MIN(t.YFZGPNYDD) AS 'YFZGPNYDD_MIN', SUM(CASE  WHEN t.YFZGPNYDD IS NULL THEN 1 ELSE 0 END) AS 'YFZGPNYDD_null_num' , MAX(t.YFZGPNYDK) AS 'YFZGPNYDK_MAX', MIN(t.YFZGPNYDK) AS 'YFZGPNYDK_MIN' , SUM(CASE  WHEN t.YFZGPNYDK IS NULL THEN 1 ELSE 0 END) AS 'YFZGPNYDK_null_num', MAX(t.DKXLBJ) AS 'DKXLBJ_MAX' , MIN(t.DKXLBJ) AS 'DKXLBJ_MIN', SUM(CASE  WHEN t.DKXLBJ IS NULL THEN 1 ELSE 0 END) AS 'DKXLBJ_null_num' , MAX(t.YZDX) AS 'YZDX_MAX', MIN(t.YZDX) AS 'YZDX_MIN' , SUM(CASE  WHEN t.YZDX IS NULL THEN 1 ELSE 0 END) AS 'YZDX_null_num', MAX(t.CNSJ) AS 'CNSJ_MAX' , MIN(t.CNSJ) AS 'CNSJ_MIN', SUM(CASE  WHEN t.CNSJ IS NULL THEN 1 ELSE 0 END) AS 'CNSJ_null_num' , MAX(t.TZYL) AS 'TZYL_MAX', MIN(t.TZYL) AS 'TZYL_MIN' , SUM(CASE  WHEN t.TZYL IS NULL THEN 1 ELSE 0 END) AS 'TZYL_null_num', MAX(t.FZJCBSCZYL) AS 'FZJCBSCZYL_MAX' , MIN(t.FZJCBSCZYL) AS 'FZJCBSCZYL_MIN', SUM(CASE  WHEN t.FZJCBSCZYL IS NULL THEN 1 ELSE 0 END) AS 'FZJCBSCZYL_null_num' , MAX(t.YCSGYL) AS 'YCSGYL_MAX', MIN(t.YCSGYL) AS 'YCSGYL_MIN' , SUM(CASE  WHEN t.YCSGYL IS NULL THEN 1 ELSE 0 END) AS 'YCSGYL_null_num', MAX(t.AQFDZYL) AS 'AQFDZYL_MAX' , MIN(t.AQFDZYL) AS 'AQFDZYL_MIN', SUM(CASE  WHEN t.AQFDZYL IS NULL THEN 1 ELSE 0 END) AS 'AQFDZYL_null_num' , MAX(t.GZTZCS) AS 'GZTZCS_MAX', MIN(t.GZTZCS) AS 'GZTZCS_MIN' , SUM(CASE  WHEN t.GZTZCS IS NULL THEN 1 ELSE 0 END) AS 'GZTZCS_null_num', MAX(t.EDDWDDLFZ) AS 'EDDWDDLFZ_MAX' , MIN(t.EDDWDDLFZ) AS 'EDDWDDLFZ_MIN', SUM(CASE  WHEN t.EDDWDDLFZ IS NULL THEN 1 ELSE 0 END) AS 'EDDWDDLFZ_null_num' , MAX(t.EDRWDDL) AS 'EDRWDDL_MAX', MIN(t.EDRWDDL) AS 'EDRWDDL_MIN' , SUM(CASE  WHEN t.EDRWDDL IS NULL THEN 1 ELSE 0 END) AS 'EDRWDDL_null_num' FROM t_sb_znyc_dlq t LEFT JOIN t_dw_bzzx_sccj t1 ON t.SCCJ = t1.SCCJBM GROUP BY t.sccj, t.xh";
		sqlNameMap.put(sql_sb_dlq, "断路器");
		String sql_sb_glkg = "SELECT t.SCCJ AS 'sccj', t1.SCCJMC AS 'sccjmc', t.XH AS 'xh', MAX(t.EDPL) AS 'EDPL_MAX' , MIN(t.EDPL) AS 'EDPL_MIN', SUM(CASE  WHEN t.EDPL IS NULL THEN 1 ELSE 0 END) AS 'EDPL_null_num' , MAX(t.RWDDL) AS 'RWDDL_MAX', MIN(t.RWDDL) AS 'RWDDL_MIN' , SUM(CASE  WHEN t.RWDDL IS NULL THEN 1 ELSE 0 END) AS 'RWDDL_null_num', MAX(t.ZHLDZ) AS 'ZHLDZ_MAX' , MIN(t.ZHLDZ) AS 'ZHLDZ_MIN', SUM(CASE  WHEN t.ZHLDZ IS NULL THEN 1 ELSE 0 END) AS 'ZHLDZ_null_num' , MAX(t.LDCJNYFZDK) AS 'LDCJNYFZDK_MAX', MIN(t.LDCJNYFZDK) AS 'LDCJNYFZDK_MIN' , SUM(CASE  WHEN t.LDCJNYFZDK IS NULL THEN 1 ELSE 0 END) AS 'LDCJNYFZDK_null_num', MAX(t.EDDL) AS 'EDDL_MAX' , MIN(t.EDDL) AS 'EDDL_MIN', SUM(CASE  WHEN t.EDDL IS NULL THEN 1 ELSE 0 END) AS 'EDDL_null_num' , MAX(t.DWDDL) AS 'DWDDL_MAX', MIN(t.DWDDL) AS 'DWDDL_MIN' , SUM(CASE  WHEN t.DWDDL IS NULL THEN 1 ELSE 0 END) AS 'DWDDL_null_num', MAX(t.EDDSNSSJ) AS 'EDDSNSSJ_MAX' , MIN(t.EDDSNSSJ) AS 'EDDSNSSJ_MIN', SUM(CASE  WHEN t.EDDSNSSJ IS NULL THEN 1 ELSE 0 END) AS 'EDDSNSSJ_null_num' , MAX(t.JDKGRWDDL) AS 'JDKGRWDDL_MAX', MIN(t.JDKGRWDDL) AS 'JDKGRWDDL_MIN' , SUM(CASE  WHEN t.JDKGRWDDL IS NULL THEN 1 ELSE 0 END) AS 'JDKGRWDDL_null_num', MAX(t.LDCJNYFZDD) AS 'LDCJNYFZDD_MAX' , MIN(t.LDCJNYFZDD) AS 'LDCJNYFZDD_MIN', SUM(CASE  WHEN t.LDCJNYFZDD IS NULL THEN 1 ELSE 0 END) AS 'LDCJNYFZDD_null_num' , MAX(t.DJZL) AS 'DJZL_MAX', MIN(t.DJZL) AS 'DJZL_MIN' , SUM(CASE  WHEN t.DJZL IS NULL THEN 1 ELSE 0 END) AS 'DJZL_null_num' FROM t_sb_znyc_glkg t LEFT JOIN t_dw_bzzx_sccj t1 ON t.SCCJ = t1.SCCJBM GROUP BY t.sccj, t.xh";
		sqlNameMap.put(sql_sb_glkg, "隔离开关");
		String sql_sb_jdbyq = "SELECT t.SCCJ AS 'sccj', t1.SCCJMC AS 'sccjmc', t.XH AS 'xh', MAX(t.EDPL) AS 'EDPL_MAX' , MIN(t.EDPL) AS 'EDPL_MIN', SUM(CASE  WHEN t.EDPL IS NULL THEN 1 ELSE 0 END) AS 'EDPL_null_num' , MAX(t.SF6QTBJYL) AS 'SF6QTBJYL_MAX', MIN(t.SF6QTBJYL) AS 'SF6QTBJYL_MIN' , SUM(CASE  WHEN t.SF6QTBJYL IS NULL THEN 1 ELSE 0 END) AS 'SF6QTBJYL_null_num', MAX(t.KZDL) AS 'KZDL_MAX' , MIN(t.KZDL) AS 'KZDL_MIN', SUM(CASE  WHEN t.KZDL IS NULL THEN 1 ELSE 0 END) AS 'KZDL_null_num' , MAX(t.DLSH) AS 'DLSH_MAX', MIN(t.DLSH) AS 'DLSH_MIN' , SUM(CASE  WHEN t.DLSH IS NULL THEN 1 ELSE 0 END) AS 'DLSH_null_num', MAX(t.LXZK) AS 'LXZK_MAX' , MIN(t.LXZK) AS 'LXZK_MIN', SUM(CASE  WHEN t.LXZK IS NULL THEN 1 ELSE 0 END) AS 'LXZK_null_num' , MAX(t.SF6QTZL) AS 'SF6QTZL_MAX', MIN(t.SF6QTZL) AS 'SF6QTZL_MIN' , SUM(CASE  WHEN t.SF6QTZL IS NULL THEN 1 ELSE 0 END) AS 'SF6QTZL_null_num', MAX(t.EDDL) AS 'EDDL_MAX' , MIN(t.EDDL) AS 'EDDL_MIN', SUM(CASE  WHEN t.EDDL IS NULL THEN 1 ELSE 0 END) AS 'EDDL_null_num' , MAX(t.EDRL) AS 'EDRL_MAX', MIN(t.EDRL) AS 'EDRL_MIN' , SUM(CASE  WHEN t.EDRL IS NULL THEN 1 ELSE 0 END) AS 'EDRL_null_num', MAX(t.ZZ) AS 'ZZ_MAX' , MIN(t.ZZ) AS 'ZZ_MIN', SUM(CASE  WHEN t.ZZ IS NULL THEN 1 ELSE 0 END) AS 'ZZ_null_num' , MAX(t.SF6QTEDYL) AS 'SF6QTEDYL_MAX', MIN(t.SF6QTEDYL) AS 'SF6QTEDYL_MIN' , SUM(CASE  WHEN t.SF6QTEDYL IS NULL THEN 1 ELSE 0 END) AS 'SF6QTEDYL_null_num', MAX(t.KZSH) AS 'KZSH_MAX' , MIN(t.KZSH) AS 'KZSH_MIN', SUM(CASE  WHEN t.KZSH IS NULL THEN 1 ELSE 0 END) AS 'KZSH_null_num' , MAX(t.QSZ) AS 'QSZ_MAX', MIN(t.QSZ) AS 'QSZ_MIN' , SUM(CASE  WHEN t.QSZ IS NULL THEN 1 ELSE 0 END) AS 'QSZ_null_num', MAX(t.FZSH) AS 'FZSH_MAX' , MIN(t.FZSH) AS 'FZSH_MIN', SUM(CASE  WHEN t.FZSH IS NULL THEN 1 ELSE 0 END) AS 'FZSH_null_num' , MAX(t.JDBZXDEDDL) AS 'JDBZXDEDDL_MAX', MIN(t.JDBZXDEDDL) AS 'JDBZXDEDDL_MIN' , SUM(CASE  WHEN t.JDBZXDEDDL IS NULL THEN 1 ELSE 0 END) AS 'JDBZXDEDDL_null_num', MAX(t.YZ) AS 'YZ_MAX' , MIN(t.YZ) AS 'YZ_MIN', SUM(CASE  WHEN t.YZ IS NULL THEN 1 ELSE 0 END) AS 'YZ_null_num' FROM t_sb_znyc_jdb t LEFT JOIN t_dw_bzzx_sccj t1 ON t.SCCJ = t1.SCCJBM GROUP BY t.sccj, t.xh";
		sqlNameMap.put(sql_sb_jdbyq, "接地变压器");
		String sql_sb_kgg = "SELECT t.SCCJ AS 'sccj', t1.SCCJMC AS 'sccjmc', t.XH AS 'xh', MAX(t.EDPL) AS 'EDPL_MAX' , MIN(t.EDPL) AS 'EDPL_MIN', SUM(CASE  WHEN t.EDPL IS NULL THEN 1 ELSE 0 END) AS 'EDPL_null_num' , MAX(t.EDDL) AS 'EDDL_MAX', MIN(t.EDDL) AS 'EDDL_MIN' , SUM(CASE  WHEN t.EDDL IS NULL THEN 1 ELSE 0 END) AS 'EDDL_null_num', MAX(t.GMKD) AS 'GMKD_MAX' , MIN(t.GMKD) AS 'GMKD_MIN', SUM(CASE  WHEN t.GMKD IS NULL THEN 1 ELSE 0 END) AS 'GMKD_null_num' FROM t_sb_znyc_kgg t LEFT JOIN t_dw_bzzx_sccj t1 ON t.SCCJ = t1.SCCJBM GROUP BY t.sccj, t.xh";
		sqlNameMap.put(sql_sb_kgg, "开关柜");
		String sql_sb_mx = "SELECT t.SCCJ AS 'sccj', t1.SCCJMC AS 'sccjmc', t.XH AS 'xh', MAX(t.EDDL) AS 'EDDL_MAX' , MIN(t.EDDL) AS 'EDDL_MIN', SUM(CASE  WHEN t.EDDL IS NULL THEN 1 ELSE 0 END) AS 'EDDL_null_num' , MAX(t.DWDDL) AS 'DWDDL_MAX', MIN(t.DWDDL) AS 'DWDDL_MIN' , SUM(CASE  WHEN t.DWDDL IS NULL THEN 1 ELSE 0 END) AS 'DWDDL_null_num', MAX(t.RWDDLSJ) AS 'RWDDLSJ_MAX' , MIN(t.RWDDLSJ) AS 'RWDDLSJ_MIN', SUM(CASE  WHEN t.RWDDLSJ IS NULL THEN 1 ELSE 0 END) AS 'RWDDLSJ_null_num' , MAX(t.MXCD) AS 'MXCD_MAX', MIN(t.MXCD) AS 'MXCD_MIN' , SUM(CASE  WHEN t.MXCD IS NULL THEN 1 ELSE 0 END) AS 'MXCD_null_num', MAX(t.EDPL) AS 'EDPL_MAX' , MIN(t.EDPL) AS 'EDPL_MIN', SUM(CASE  WHEN t.EDPL IS NULL THEN 1 ELSE 0 END) AS 'EDPL_null_num' , MAX(t.RWDDL) AS 'RWDDL_MAX', MIN(t.RWDDL) AS 'RWDDL_MIN' , SUM(CASE  WHEN t.RWDDL IS NULL THEN 1 ELSE 0 END) AS 'RWDDL_null_num' FROM t_sb_znyc_mx t LEFT JOIN t_dw_bzzx_sccj t1 ON t.SCCJ = t1.SCCJBM GROUP BY t.sccj, t.xh";
		sqlNameMap.put(sql_sb_mx, "母线");
		String sql_sb_ohdrq = "SELECT t.SCCJ AS 'sccj', t1.SCCJMC AS 'sccjmc', t.XH AS 'xh', MAX(t.EDPL) AS 'EDPL_MAX' , MIN(t.EDPL) AS 'EDPL_MIN', SUM(CASE  WHEN t.EDPL IS NULL THEN 1 ELSE 0 END) AS 'EDPL_null_num' , MAX(t.AZJS) AS 'AZJS_MAX', MIN(t.AZJS) AS 'AZJS_MIN' , SUM(CASE  WHEN t.AZJS IS NULL THEN 1 ELSE 0 END) AS 'AZJS_null_num', MAX(t.ZJMPDRL) AS 'ZJMPDRL_MAX' , MIN(t.ZJMPDRL) AS 'ZJMPDRL_MIN', SUM(CASE  WHEN t.ZJMPDRL IS NULL THEN 1 ELSE 0 END) AS 'ZJMPDRL_null_num' , MAX(t.GD) AS 'GD_MAX', MIN(t.GD) AS 'GD_MIN' , SUM(CASE  WHEN t.GD IS NULL THEN 1 ELSE 0 END) AS 'GD_null_num', MAX(t.ZEDDRL) AS 'ZEDDRL_MAX' , MIN(t.ZEDDRL) AS 'ZEDDRL_MIN', SUM(CASE  WHEN t.ZEDDRL IS NULL THEN 1 ELSE 0 END) AS 'ZEDDRL_null_num' , MAX(t.PDBJ) AS 'PDBJ_MAX', MIN(t.PDBJ) AS 'PDBJ_MIN' , SUM(CASE  WHEN t.PDBJ IS NULL THEN 1 ELSE 0 END) AS 'PDBJ_null_num', MAX(t.SJMPDRL) AS 'SJMPDRL_MAX' , MIN(t.SJMPDRL) AS 'SJMPDRL_MIN', SUM(CASE  WHEN t.SJMPDRL IS NULL THEN 1 ELSE 0 END) AS 'SJMPDRL_null_num' , MAX(t.XJMPDRL) AS 'XJMPDRL_MAX', MIN(t.XJMPDRL) AS 'XJMPDRL_MIN' , SUM(CASE  WHEN t.XJMPDRL IS NULL THEN 1 ELSE 0 END) AS 'XJMPDRL_null_num' FROM t_sb_znyc_ohdrq t LEFT JOIN t_dw_bzzx_sccj t1 ON t.SCCJ = t1.SCCJBM GROUP BY t.sccj, t.xh";
		sqlNameMap.put(sql_sb_ohdrq, "耦合电容器");
		String sql_sb_pdbyq = "SELECT t.SCCJ AS 'sccj', t1.SCCJMC AS 'sccjmc', t.XH AS 'xh', MAX(t.ZKDY) AS 'ZKDY_MAX' , MIN(t.ZKDY) AS 'ZKDY_MIN', SUM(CASE  WHEN t.ZKDY IS NULL THEN 1 ELSE 0 END) AS 'ZKDY_null_num' , MAX(t.DLSH) AS 'DLSH_MAX', MIN(t.DLSH) AS 'DLSH_MIN' , SUM(CASE  WHEN t.DLSH IS NULL THEN 1 ELSE 0 END) AS 'DLSH_null_num', MAX(t.GYCEDDL) AS 'GYCEDDL_MAX' , MIN(t.GYCEDDL) AS 'GYCEDDL_MIN', SUM(CASE  WHEN t.GYCEDDL IS NULL THEN 1 ELSE 0 END) AS 'GYCEDDL_null_num' , MAX(t.ZZ) AS 'ZZ_MAX', MIN(t.ZZ) AS 'ZZ_MIN' , SUM(CASE  WHEN t.ZZ IS NULL THEN 1 ELSE 0 END) AS 'ZZ_null_num', MAX(t.JDDZ) AS 'JDDZ_MAX' , MIN(t.JDDZ) AS 'JDDZ_MIN', SUM(CASE  WHEN t.JDDZ IS NULL THEN 1 ELSE 0 END) AS 'JDDZ_null_num' , MAX(t.EDRL) AS 'EDRL_MAX', MIN(t.EDRL) AS 'EDRL_MIN' , SUM(CASE  WHEN t.EDRL IS NULL THEN 1 ELSE 0 END) AS 'EDRL_null_num', MAX(t.KZDL) AS 'KZDL_MAX' , MIN(t.KZDL) AS 'KZDL_MIN', SUM(CASE  WHEN t.KZDL IS NULL THEN 1 ELSE 0 END) AS 'KZDL_null_num' , MAX(t.KZSH) AS 'KZSH_MAX', MIN(t.KZSH) AS 'KZSH_MIN' , SUM(CASE  WHEN t.KZSH IS NULL THEN 1 ELSE 0 END) AS 'KZSH_null_num', MAX(t.DYCEDDL) AS 'DYCEDDL_MAX' , MIN(t.DYCEDDL) AS 'DYCEDDL_MIN', SUM(CASE  WHEN t.DYCEDDL IS NULL THEN 1 ELSE 0 END) AS 'DYCEDDL_null_num' FROM t_sb_znyc_pdbyq t LEFT JOIN t_dw_bzzx_sccj t1 ON t.SCCJ = t1.SCCJBM GROUP BY t.sccj, t.xh";
		sqlNameMap.put(sql_sb_pdbyq, "配电变压器");
		String sql_sb_sybyq = "SELECT t.SCCJ AS 'sccj', t1.SCCJMC AS 'sccjmc', t.XH AS 'xh', MAX(t.EDPL) AS 'EDPL_MAX' , MIN(t.EDPL) AS 'EDPL_MIN', SUM(CASE  WHEN t.EDPL IS NULL THEN 1 ELSE 0 END) AS 'EDPL_null_num' , MAX(t.SF6QTBJYL) AS 'SF6QTBJYL_MAX', MIN(t.SF6QTBJYL) AS 'SF6QTBJYL_MIN' , SUM(CASE  WHEN t.SF6QTBJYL IS NULL THEN 1 ELSE 0 END) AS 'SF6QTBJYL_null_num', MAX(t.KZDL) AS 'KZDL_MAX' , MIN(t.KZDL) AS 'KZDL_MIN', SUM(CASE  WHEN t.KZDL IS NULL THEN 1 ELSE 0 END) AS 'KZDL_null_num' , MAX(t.DLSH) AS 'DLSH_MAX', MIN(t.DLSH) AS 'DLSH_MIN' , SUM(CASE  WHEN t.DLSH IS NULL THEN 1 ELSE 0 END) AS 'DLSH_null_num', MAX(t.SF6QTZL) AS 'SF6QTZL_MAX' , MIN(t.SF6QTZL) AS 'SF6QTZL_MIN', SUM(CASE  WHEN t.SF6QTZL IS NULL THEN 1 ELSE 0 END) AS 'SF6QTZL_null_num' , MAX(t.EDDL) AS 'EDDL_MAX', MIN(t.EDDL) AS 'EDDL_MIN' , SUM(CASE  WHEN t.EDDL IS NULL THEN 1 ELSE 0 END) AS 'EDDL_null_num', MAX(t.EDRL) AS 'EDRL_MAX' , MIN(t.EDRL) AS 'EDRL_MIN', SUM(CASE  WHEN t.EDRL IS NULL THEN 1 ELSE 0 END) AS 'EDRL_null_num' , MAX(t.ZZ) AS 'ZZ_MAX', MIN(t.ZZ) AS 'ZZ_MIN' , SUM(CASE  WHEN t.ZZ IS NULL THEN 1 ELSE 0 END) AS 'ZZ_null_num', MAX(t.SF6QTEDYL) AS 'SF6QTEDYL_MAX' , MIN(t.SF6QTEDYL) AS 'SF6QTEDYL_MIN', SUM(CASE  WHEN t.SF6QTEDYL IS NULL THEN 1 ELSE 0 END) AS 'SF6QTEDYL_null_num' , MAX(t.KZSH) AS 'KZSH_MAX', MIN(t.KZSH) AS 'KZSH_MIN' , SUM(CASE  WHEN t.KZSH IS NULL THEN 1 ELSE 0 END) AS 'KZSH_null_num', MAX(t.QSZ) AS 'QSZ_MAX' , MIN(t.QSZ) AS 'QSZ_MIN', SUM(CASE  WHEN t.QSZ IS NULL THEN 1 ELSE 0 END) AS 'QSZ_null_num' , MAX(t.YZ) AS 'YZ_MAX', MIN(t.YZ) AS 'YZ_MIN' , SUM(CASE  WHEN t.YZ IS NULL THEN 1 ELSE 0 END) AS 'YZ_null_num' FROM t_sb_znyc_syb t LEFT JOIN t_dw_bzzx_sccj t1 ON t.SCCJ = t1.SCCJBM GROUP BY t.sccj, t.xh";
		sqlNameMap.put(sql_sb_sybyq, "所用变压器/柜");
		String sql_sb_xhxq = "SELECT t.SCCJ AS 'sccj', t1.SCCJMC AS 'sccjmc', t.XH AS 'xh', MAX(t.ZNDZ) AS 'ZNDZ_MAX' , MIN(t.ZNDZ) AS 'ZNDZ_MIN', SUM(CASE  WHEN t.ZNDZ IS NULL THEN 1 ELSE 0 END) AS 'ZNDZ_null_num' , MAX(t.EDRL) AS 'EDRL_MAX', MIN(t.EDRL) AS 'EDRL_MIN' , SUM(CASE  WHEN t.EDRL IS NULL THEN 1 ELSE 0 END) AS 'EDRL_null_num', MAX(t.YZDX) AS 'YZDX_MAX' , MIN(t.YZDX) AS 'YZDX_MIN', SUM(CASE  WHEN t.YZDX IS NULL THEN 1 ELSE 0 END) AS 'YZDX_null_num' , MAX(t.EDPL) AS 'EDPL_MAX', MIN(t.EDPL) AS 'EDPL_MIN' , SUM(CASE  WHEN t.EDPL IS NULL THEN 1 ELSE 0 END) AS 'EDPL_null_num', MAX(t.EDDK) AS 'EDDK_MAX' , MIN(t.EDDK) AS 'EDDK_MIN', SUM(CASE  WHEN t.EDDK IS NULL THEN 1 ELSE 0 END) AS 'EDDK_null_num' , MAX(t.XDY) AS 'XDY_MAX', MIN(t.XDY) AS 'XDY_MIN' , SUM(CASE  WHEN t.XDY IS NULL THEN 1 ELSE 0 END) AS 'XDY_null_num' FROM t_sb_znyc_xhzz t LEFT JOIN t_dw_bzzx_sccj t1 ON t.SCCJ = t1.SCCJBM GROUP BY t.sccj, t.xh";
		sqlNameMap.put(sql_sb_xhxq, "消弧线圈");
		String sql_sb_zndldl = "SELECT t.SCCJ AS 'sccj', t1.SCCJMC AS 'sccjmc', t.XH AS 'xh', MAX(t.EDDL) AS 'EDDL_MAX' , MIN(t.EDDL) AS 'EDDL_MIN', SUM(CASE  WHEN t.EDDL IS NULL THEN 1 ELSE 0 END) AS 'EDDL_null_num' , MAX(t.CD) AS 'CD_MAX', MIN(t.CD) AS 'CD_MIN' , SUM(CASE  WHEN t.CD IS NULL THEN 1 ELSE 0 END) AS 'CD_null_num', MAX(t.JMJ) AS 'JMJ_MAX' , MIN(t.JMJ) AS 'JMJ_MIN', SUM(CASE  WHEN t.JMJ IS NULL THEN 1 ELSE 0 END) AS 'JMJ_null_num' FROM t_sb_znyc_zndl t LEFT JOIN t_dw_bzzx_sccj t1 ON t.SCCJ = t1.SCCJBM GROUP BY t.sccj, t.xh";
		sqlNameMap.put(sql_sb_zndldl, "站内电力电缆");
		String sql_sb_zhdq = "SELECT t.SCCJ AS 'sccj', t1.SCCJMC AS 'sccjmc', t.XH AS 'xh', MAX(t.SF6QTEDYLFDLQQS) AS 'SF6QTEDYLFDLQQS_MAX' , MIN(t.SF6QTEDYLFDLQQS) AS 'SF6QTEDYLFDLQQS_MIN', SUM(CASE  WHEN t.SF6QTEDYLFDLQQS IS NULL THEN 1 ELSE 0 END) AS 'SF6QTEDYLFDLQQS_null_num' , MAX(t.SF6QTYLJDBJYLFDLQQS) AS 'SF6QTYLJDBJYLFDLQQS_MAX', MIN(t.SF6QTYLJDBJYLFDLQQS) AS 'SF6QTYLJDBJYLFDLQQS_MIN' , SUM(CASE  WHEN t.SF6QTYLJDBJYLFDLQQS IS NULL THEN 1 ELSE 0 END) AS 'SF6QTYLJDBJYLFDLQQS_null_num', MAX(t.EDDL) AS 'EDDL_MAX' , MIN(t.EDDL) AS 'EDDL_MIN', SUM(CASE  WHEN t.EDDL IS NULL THEN 1 ELSE 0 END) AS 'EDDL_null_num' , MAX(t.RWDDL) AS 'RWDDL_MAX', MIN(t.RWDDL) AS 'RWDDL_MIN' , SUM(CASE  WHEN t.RWDDL IS NULL THEN 1 ELSE 0 END) AS 'RWDDL_null_num', MAX(t.RWDCXSJ) AS 'RWDCXSJ_MAX' , MIN(t.RWDCXSJ) AS 'RWDCXSJ_MIN', SUM(CASE  WHEN t.RWDCXSJ IS NULL THEN 1 ELSE 0 END) AS 'RWDCXSJ_null_num' FROM t_sb_znyc_zhdq t LEFT JOIN t_dw_bzzx_sccj t1 ON t.SCCJ = t1.SCCJBM GROUP BY t.sccj, t.xh";
		sqlNameMap.put(sql_sb_zhdq, "组合电器");
		String name = null;
		// 清空表再执行统计
		cleanTable_datastatistic();
		// 遍历执行
		for (String s : sqlNameMap.keySet()) {
			name = sqlNameMap.get(s);
			cleanAndTranslateData(s, name);
		}
		System.out.println("finish");
	}

}
